---
- include_vars: ../../create_net_docker/defaults/main.yaml

- name: Log into DockerHub
  docker_login:
    username: "{{ login_dockerhub }}"
    password: "{{ password_dockerhub }}"
    email: "{{ email_dockerhub }}"

- name: Run web app container
  docker_container:
    name: "web_app_{{ item }}"
    state: started
    image: "{{ docker_image_wep_app }}"
    pull: true
    networks_cli_compatible: yes
    networks:
      - name: "{{ network_ansible_web }}"
    ports:
      - "{{ item }}:5000"
  loop: "{{ docker_ports }}"
