---
- name: Template a file to /etc/nginx/nginx.conf
  ansible.builtin.template:
    src: "{{ template_nginx_src }}"
    dest: "{{ template_nginx_dest }}"
  notify: restart nginx docker
  
- name: restart nginx docker
  docker_container:
    name: "{{ name_docker_nginx }}"
    state: started
    image: nginx
    pull: true
    networks_cli_compatible: yes
    networks:
      - name: "{{ network_ansible_web }}"
    volumes:
      - "{{ volumes_nginx }}"
    ports:
      - "{{ portn_nginx }}"
